// A way in for automated testing, and nothing else.
//
// Verifying a signed-in screen otherwise needs a human to type a password into
// a browser. This mints a session for a nominated account instead — which is
// convenient, and for exactly the same reason would be a total account takeover
// if it ever reached a deployed environment.
//
// So it is guarded four ways over, each of which alone would be enough:
//
//   1. The route is not registered unless DEV_LOGIN_SECRET is set. With no
//      secret there is no endpoint — not a 403, nothing to find.
//   2. The server refuses to boot with that secret set and NODE_ENV=production
//      (see server.ts). Misconfiguration is loud and immediate rather than
//      silent and permanent.
//   3. The request must come from the loopback interface. Not a header, not a
//      hostname — the socket's own remote address, so it cannot be reached by
//      an X-Forwarded-For or a Host trick from off-box.
//   4. The account must be named in DEV_LOGIN_ACCOUNTS. There is no wildcard,
//      so a leaked secret buys sessions for the accounts you nominated and
//      never for anyone else.
//
// Where the API runs is a separate question from which database it talks to: a
// dev process on a laptop can be pointed at a production Supabase, and in this
// repository it is. Guard 4 is what contains that, which is why it has no
// escape hatch.
//
// Note what this does NOT do: it never sets a password. An earlier draft reset
// one to mint the session, which works for a throwaway account and locks a real
// person out of theirs. A magic-link token generated by the admin API and
// redeemed immediately leaves the account exactly as it was found.

import { createClient } from '@supabase/supabase-js'
import type { FastifyInstance, FastifyRequest } from 'fastify'
import { z } from 'zod'
import { env } from '../env.js'
import { badRequest, HttpError } from '../errors.js'

const bodySchema = z.object({
  secret: z.string().min(1),
  /** Either identifies the account. Both are checked against the allow-list. */
  email: z.string().email().optional(),
  userId: z.string().uuid().optional(),
})

/** True only for a socket that really is on this machine. */
function isLoopback(request: FastifyRequest): boolean {
  const ip = request.socket.remoteAddress ?? ''
  return ip === '::1' || ip === '::ffff:127.0.0.1' || ip.startsWith('127.')
}

function adminClient() {
  if (!env.SUPABASE_SERVICE_ROLE_KEY) {
    throw new HttpError(503, 'Dev login needs a service role key', 'not_configured')
  }
  return createClient(env.SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY, {
    auth: { autoRefreshToken: false, persistSession: false },
  })
}

// Redeeming the token uses the same client: `verify` is a public auth endpoint
// and the service key is a valid apikey for it, so this needs no anon key of
// its own. One less thing to configure is one less thing to configure wrongly.

export async function devLoginRoutes(app: FastifyInstance): Promise<void> {
  const secret = env.DEV_LOGIN_SECRET
  if (!secret) return

  app.post('/dev/login', async (request) => {
    // Deliberately 404 rather than 403 on the first two checks: an endpoint
    // that admits to existing is a thing to come back and attack.
    if (!isLoopback(request)) throw new HttpError(404, 'No such endpoint', 'not_found')

    const body = bodySchema.safeParse(request.body)
    if (!body.success) throw badRequest('Send a secret and either an email or a userId')

    const given = Buffer.from(body.data.secret)
    const want = Buffer.from(secret)
    if (given.length !== want.length || !given.equals(want)) {
      throw new HttpError(404, 'No such endpoint', 'not_found')
    }

    const email = body.data.email?.trim().toLowerCase()
    const userId = body.data.userId
    if (!email && !userId) throw badRequest('Send either an email or a userId')

    const allowed = env.DEV_LOGIN_ACCOUNTS
    const named = [email, userId].filter(Boolean) as string[]
    if (!named.some((n) => allowed.includes(n.toLowerCase()))) {
      request.log.warn({ named }, 'dev login refused: account is not on DEV_LOGIN_ACCOUNTS')
      throw new HttpError(
        403,
        'That account is not on DEV_LOGIN_ACCOUNTS. Dev login only works for accounts you have nominated.',
        'not_allowed',
      )
    }

    const admin = adminClient()

    // Resolve to an address, since generateLink works by email.
    let address = email
    if (!address && userId) {
      const { data, error } = await admin.auth.admin.getUserById(userId)
      if (error || !data.user?.email) {
        throw new HttpError(404, 'No such account', 'not_found')
      }
      address = data.user.email
    }

    // A one-shot token for an existing account, redeemed straight away. The
    // account's password, metadata and sessions are left untouched.
    const { data: link, error: linkError } = await admin.auth.admin.generateLink({
      type: 'magiclink',
      email: address!,
    })
    if (linkError || !link.properties?.hashed_token) {
      throw new HttpError(500, `Could not mint a token: ${linkError?.message ?? 'no token'}`)
    }

    const { data: session, error: verifyError } = await admin.auth.verifyOtp({
      token_hash: link.properties.hashed_token,
      type: 'email',
    })
    if (verifyError || !session.session) {
      throw new HttpError(500, `Could not redeem the token: ${verifyError?.message ?? ''}`)
    }

    request.log.warn({ address }, 'DEV LOGIN USED — a session was minted without a password')

    return {
      email: address,
      userId: session.user?.id ?? null,
      session: {
        accessToken: session.session.access_token,
        refreshToken: session.session.refresh_token,
        expiresIn: session.session.expires_in,
        expiresAt: session.session.expires_at,
      },
    }
  })
}
